{% set custom_fields %}
  couchdb.doc->'fields'->'inputs'->>'contact,name' AS household_name,
  couchdb.doc->'fields'->'inputs'->>'contact,contact,_id' AS household_head_id,
  couchdb.doc->'fields'->'inputs'->>'contact,contact,phone' AS household_head_phone,
  couchdb.doc->'fields'->'group_fuel'->>'cooking_fuel' AS cooking_fuel,
  couchdb.doc->'fields'->'group_fuel'->>'lighting_fuel' AS lighting_fuel,
  couchdb.doc->'fields'->'group_wash'->>'piped_water' AS piped_water,
  couchdb.doc->'fields'->'group_wash'->>'pit_latrine' AS pit_latrine,
  couchdb.doc->'fields'->'group_wash'->>'share_toilet' AS shares_toilet,
  couchdb.doc->'fields'->'group_wash'->>'water_source' AS water_source,
  couchdb.doc->'fields'->'group_wash'->>'human_waste_disposal' AS human_waste_disposal,
  couchdb.doc->'fields'->'group_social_assistance'->>'skipped_meals_money' AS skipped_meals_lack_of_money,
  couchdb.doc->'fields'->'group_social_assistance'->>'receive_benefits_sap' AS social_assistance_program_benefits,
  couchdb.doc->'fields'->'group_house_asset_ownership'->>'assets' AS assets,
  couchdb.doc->'fields'->'group_house_asset_ownership'->>'livestock' AS livestock,
  couchdb.doc->'fields'->'group_house_asset_ownership'->>'member_own_land' AS member_own_land,
  couchdb.doc->'fields'->'group_house_asset_ownership'->>'household_conditions' AS house_conditions,
  couchdb.doc->'fields'->'group_house_asset_ownership'->>'count_deaths_last_12_months' AS deaths_last_12_months,
  couchdb.doc->'fields'->'group_house_asset_ownership'->>'count_live_births_last_12_months' AS live_births_last_12_months,
  couchdb.doc->'fields'->'group_dwelling_and_household'->>'wall_type' AS wall_type,
  couchdb.doc->'fields'->'group_dwelling_and_household'->>'floor_type' AS floor_type,
  couchdb.doc->'fields'->'group_dwelling_and_household'->>'owns_house' AS owns_house,
  couchdb.doc->'fields'->'group_dwelling_and_household'->>'no_of_rooms' AS no_of_rooms,
  couchdb.doc->'fields'->'group_dwelling_and_household'->>'dwelling_risk' AS dwelling_is_at_risk_of,
  couchdb.doc->'fields'->'group_dwelling_and_household'->>'finished_wall' AS finished_wall,
  couchdb.doc->'fields'->'group_dwelling_and_household'->>'natural_floor' AS natural_floor,
  couchdb.doc->'fields'->'group_dwelling_and_household'->>'roofing_material' AS roofing_material,
  couchdb.doc->'fields'->'group_dwelling_and_household'->>'n_housing_material' AS other_roofing_material,
  couchdb.doc->'fields'->'group_geographic_identification'->>'area_type' AS area_type,
  couchdb.doc->'fields'->'group_geographic_identification'->>'residence_duration_years' AS residence_duration_years,
  couchdb.doc->'fields'->'group_geographic_identification'->>'residence_duration_months' AS residence_duration_months

{% endset %}
{{ cht_form_model('socio_economic_survey', custom_fields, []) }}
